#ifndef SYSTEM_CONFIG_H
#define SYSTEM_CONFIG_H

#include "xil_types.h"
#include "xparameters.h"

namespace app
{
namespace config
{

/* Hardware identifiers generated by the current ZCU104 R5 platform. */
constexpr UINTPTR kTemperatureBaseAddress =
    static_cast<UINTPTR>(XPAR_TEMPERATURE_MOCK_0_S_AXI_BASEADDR);
constexpr u32 kTemperatureInterruptId =
    XPAR_FABRIC_TEMPERATURE_MOCK_0_IRQ_INTR;
constexpr u16 kGicDeviceId = XPAR_SCUGIC_0_DEVICE_ID;
constexpr u16 kGpioDeviceId = XPAR_AXI_GPIO_0_DEVICE_ID;
constexpr u16 kI2cDeviceId = XPAR_XIICPS_0_DEVICE_ID;

/* ZCU104 EEPROM connection. */
constexpr u16 kEepromI2cAddress = 0x50U;
constexpr u32 kEepromI2cClockHz = 100000U;
constexpr u16 kEepromRevisionOffset = 0x0000U;
constexpr u16 kEepromSerialOffset = 0x0001U;

/* AXI GPIO channel and LED mapping. */
constexpr u32 kGpioChannel = 1U;
constexpr u32 kLedGreenMask = 0x00000001U;
constexpr u32 kLedYellowMask = 0x00000002U;
constexpr u32 kLedRedMask = 0x00000004U;
constexpr u32 kLedAllMask =
    kLedGreenMask | kLedYellowMask | kLedRedMask;

/* The IP holds IRQ high until status bit 0 is acknowledged. */
constexpr u8 kTemperatureIrqPriority = 0xA0U;
constexpr u8 kTemperatureIrqTriggerType = 0x01U; /* level-sensitive */

/* Limits in tenths of one degree Celsius. */
constexpr s32 kCriticalLowX10 = 50;
constexpr s32 kWarningX10 = 850;
constexpr s32 kCriticalHighX10 = 1050;

/*
 * Matches the current C application's behavior while the physical EEPROM
 * layout is being debugged. Set this to false for strict production behavior.
 */
constexpr bool kAllowEepromFallback = true;

} // namespace config
} // namespace app

#endif
