#ifndef SYSTEM_MANAGER_H
#define SYSTEM_MANAGER_H

typedef enum
{
    SYSTEM_MANAGER_SUCCESS = 0,
    SYSTEM_MANAGER_INVALID_ARGUMENT,
    SYSTEM_MANAGER_GPIO_INITIALIZATION_ERROR,
    SYSTEM_MANAGER_EEPROM_INITIALIZATION_ERROR,
    SYSTEM_MANAGER_CONFIGURATION_READ_ERROR,
    SYSTEM_MANAGER_TEMPERATURE_INITIALIZATION_ERROR,
    SYSTEM_MANAGER_GIC_INITIALIZATION_ERROR,
    SYSTEM_MANAGER_INTERRUPT_INITIALIZATION_ERROR,
    SYSTEM_MANAGER_SENSOR_SCALE_MISMATCH,
    SYSTEM_MANAGER_TEMPERATURE_READ_ERROR,
    SYSTEM_MANAGER_GPIO_UPDATE_ERROR
} SystemManagerStatus;

SystemManagerStatus SystemManager_Initialize(void);

SystemManagerStatus SystemManager_Process(void);

#endif
